<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5bi46KeB6Zeu6aKY');
$cfg_Cs[2]=array(0,1,1,'5Zyo57q/5omL5YaM');
$cfg_Cs[3]=array(2,1,1,'57O757uf6K6+572u');
$cfg_Cs[4]=array(2,1,1,'56ev5YiG5ZWG5Z+O');
$cfg_Cs[5]=array(2,1,0,'55+t5L+h5o+Q6YaS');
$cfg_Cs[6]=array(1,1,1,'5b+r6YCf5YWl6Zeo');
$cfg_Cs[7]=array(1,1,1,'5bi46KeB6Zeu6aKY');
$cfg_Cs[8]=array(0,1,1,'5L2/55So6aG755+l');
$cfg_Cs[9]=array(8,1,1,'5ZSu5YmN6aG755+l');
$cfg_Cs[10]=array(8,1,1,'5L2/55So6aG755+l');
$cfg_Cs[11]=array(8,1,1,'5pyA6L+R5pu05paw');
$cfg_Cs[12]=array(1,1,1,'5bqU55So566h55CG');
$cfg_Cs[13]=array(2,1,1,'5pW054K556eS5p2A');
$cfg_Cs[14]=array(2,1,1,'5bi455So5Yqf6IO9');
?>