<?php
$z[0]=Array("typeurl","",81,97);
$z[0][4]=array();
$z[1]=Array("typename","",99,116);
$z[1][4]=array();
$z[2]=Array("arcid"," @me = GetChannelArclist(@me, '<li><a href=\"[arcurl]\" title=\"[title]\">[title]</a></li>',\"flag='h' AND\", \"0,3\");",190,342);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("typeurl","",394,410);
$z[3][4]=array();
$z[4]=Array("id"," @me = GetTotalArc(@me);",458,517);
$z[4][4]=array();
$z[4][4]['runphp']="yes";

?>