<?php
$z[0]=Array("noteinfo","",0,202);
$z[0][4]=array();
$z[0][4]['notename']="http://wiki.we7shop.cn/hc";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://wiki.we7shop.cn/hc/kb/article";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://wiki.we7shop.cn/hc/kb/article/152901{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}http://wiki.we7shop.cn/hc/kb/article{/dede:areastart}\r\n    {dede:areaend}{/dede:areaend}\r\n",206,688);
$z[1][4]=array();
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://wiki.we7shop.cn/hc/kb/article/*";
$z[1][4]['startid']="1";
$z[1][4]['endid']="";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="article";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>