<div class="category-section category-22414">
                    <h2><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></h2>
                    <ul>
                        {dede:artlist type='son' noself='yes'}
                        <li class="section-86740">
                            <h3><a href="[field:typeurl/]" >[field:typename/]</a></h3>
                        </li>
                        {/dede:artlist}
                    </ul>
                </div>