<?php
$z[0]=Array("typeurl","",81,97);
$z[0][4]=array();
$z[1]=Array("typename","",99,116);
$z[1][4]=array();
$z[2]=Array("id"," @me = GetChannelArclist(@me, '<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>',\"flag='h'\", \"0,3\");",274,437);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("typeurl","",489,505);
$z[3][4]=array();
$z[4]=Array("id"," @me = GetTotalArc(@me) ; @me = '查看全部'.@me.'篇文档';",541,639);
$z[4][4]=array();
$z[4][4]['runphp']="yes";

?>