<div class="section section-86785">
                            <h3><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></h3>
                            <ul class="article-list">
                                {dede:artlist type='son' noself='yes' row="3"}
                                    <li ><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></li>
                                {/dede:artlist}
                            </ul>
                            <a href="../../section/86785/index.htm" class="more">查看全部13篇文档</a>
                        </div>