<?php
$z[0]=Array("field","",72,100);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",102,131);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","\r\n                <li class=\"section-86740\">\r\n                    <h3><a href=\"[field:typeurl/]\">[field:typename/]</a></h3>\r\n                </li>\r\n                ",176,499);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentstyle']="<li class=\"section-86740\"><h3><a href=\"[field:typeurl/]\" class=\"active\">[field:typename/]</a></h3></li>";

?>