<li class="">
                      <span class="posts-item-vote-state">[field:scores/] 赞</span>
                      <div class="posts-item-content">
                          <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                          <p>
                            <span class="author">[field.writer/]</span> • <time>发表于[field:pubdate function="GetDateTimeMK(@me)"/]</time> • <span>[field:click/]  点击</span>
                          </p>
                      </div>
                    </li>