<div class="category category-22414">
              <h2><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a></h2>
              {dede:channel type='son' noself='yes'}
              <div class="section section-86740">
                <h3 ><a href="[field:typeurl/]">[field:typename/]</a></h3>
                  <ul class="article-list"><li >
                    <li>123</li>
                  </ul>
              </div>
              {/dede:channel}
                  <a href="[field:typeurl/]" class="more">查看全部篇文档</a>
          </div>