<?php
$z[0]=Array("field","",77,105);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",107,136);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("artlist","\n                                    <li ><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\n                                ",232,432);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>