<?php
$z[0]=Array("typeurl","",81,97);
$z[0][4]=array();
$z[1]=Array("typename","",99,116);
$z[1][4]=array();
$z[2]=Array("id"," @me = GetChannelArclist(@me, '<li><a href=\"[arcurl]\" title=\"[title]\">[title]</a></li>',\"flag='h'\", \"0,3\");",274,416);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("typeurl","",468,484);
$z[3][4]=array();
$z[4]=Array("id"," @me = GetTotalArc(@me) ; @me = '查看全部'.@me.'篇文档';",520,618);
$z[4][4]=array();
$z[4][4]['runphp']="yes";

?>