<?php
$z[0]=Array("field","",71,99);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",101,130);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","\n                 <li><a href='[field:typelink/]'>[field:typename/]</a> </li>\n                ",173,383);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['currentsytle']="<li><a href='~typelink~' class='active'>~typename~</a> </li>";
$z[3]=Array("channel","\n                <li class=\"section-86740\">\n                    <h3><a href=\"[field:typeurl/]\">[field:typename/]</a></h3>\n                </li>\n                ",401,720);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['currentstyle']="<li class=\"section-86740\"><h3><a href=\"[field:typeurl/]\" class=\"active\">[field:typename/]</a></h3></li>";

?>