
              <div class="section section-86740">
                <h3 ><a href="[field:typeurl/]">[field:typename/]</a></h3>
                  <ul class="article-list"><li >
                    {dede:sql sql='Select * from `dede_arctype` where reid=~id~ ORDER BY id'}
                      <a href="javascript:;" title="人人商城售前咨询问题集锦">人人商城售前咨询问题集锦</a></li>
                    {/dede:sql}
                  </ul>
                  <a href="[field:typeurl/]" class="more">
                    查看全部[field:typeid  runphp='yes'] @me = GetTotalArc(@me);[/field:typeid]篇文档
                  </a>
              </div>
              