
              <div class="section section-86740">
                <h3 ><a href="[field:typeurl/]">[field:typename/]</a></h3>
                  <ul class="article-list"><li >
                    {dede:arclist row=3 flag='h'}
                      <a href="javascript:;" title="人人商城售前咨询问题集锦">人人商城售前咨询问题集锦</a></li>
                    {/dede:arclist}
                  </ul>
                  <a href="[field:typeurl/]" class="more">
                    查看全部[field:asd runphp='yes'] @me = GetTotalArc(@me);[/field:asd]篇文档
                  </a>
              </div>
              