<?php
$z[0]=Array("typeurl","",81,97);
$z[0][4]=array();
$z[1]=Array("typename","",99,116);
$z[1][4]=array();
$z[2]=Array("arclist"," @me = GetChannelArclist(@me);[/field:articleList]\n                    <li><a href=\"javascript:;\" title=\"人人商城售前咨询问题集锦\">人人商城售前咨询问题集锦</a></li>\n                  </ul>\n                  <a href=\"[field:typeurl",190,475);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[3]=Array("id"," @me = GetTotalArc(@me);",523,582);
$z[3][4]=array();
$z[3][4]['runphp']="yes";

?>