{dede:noteinfo notename="http://wiki.we7shop.cn/hc" channelid="1" macthtype="string"
refurl="http://wiki.we7shop.cn/hc/kb/article/152901" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://wiki.we7shop.cn/hc/kb/article/*"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://wiki.we7shop.cn/hc/kb/article/152901{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}http://wiki.we7shop.cn/hc/kb/article/152901/{/dede:areastart}
    {dede:areaend}{/dede:areaend}
{/dede:listrule}
