<?php
$z[0]=Array("field","",79,107);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",109,138);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","\n                        <li class=\"section-86740\">\n                            <h3><a href=\"[field:typeurl/]\">[field:typename/]</a></h3>\n                        </li>\n                        ",197,442);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>