<?php
$z[0]=Array("global","",474,500);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",545,575);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",613,640);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",3305,3331);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("channel","\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\n      	",3482,3724);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<li class='active'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>