<?php
$z[0]=Array("include","",0,35);
$z[0][4]=array();
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",47,88);
$z[1][4]=array();
$z[1][4]['filename']="search_bar.htm";
$z[2]=Array("include","",170,209);
$z[2][4]=array();
$z[2][4]['filename']="left_bar.htm";
$z[3]=Array("list","\r\n                    <li class=\"\">\r\n                      <span class=\"posts-item-vote-state\">[field:scores/] 赞</span>\r\n                      <div class=\"posts-item-content\">\r\n                          <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                          <p>\r\n                            <span class=\"author\">[field:writer/]</span> • <time>发表于[field:pubdate function=\"GetDateTimeMK(@me)\"/]</time> • <span>[field:click/]  点击</span>\r\n                          </p>\r\n                      </div>\r\n                    </li>\r\n                  ",658,1279);
$z[3][4]=array();
$z[3][4]['pagesize']="10";
$z[4]=Array("pagelist","",1402,1469);
$z[4][4]=array();
$z[4][4]['listitem']="index,end,pre,next,pageno";
$z[4][4]['listsize']="2";
$z[5]=Array("include","",3643,3680);
$z[5][4]=array();
$z[5][4]['filename']="footer.htm";

?>